/**
 * @file Defines the internal data structures and types for the Lambda Engine.
 * It imports shared data structures from the @shared module and defines
 * types specific to the engine's orchestration and AI processing logic.
 */

import type {
    Database,
    PlatformOutput,
    UserSignalStrength,
    Prompt,
    User,
    ForumUser,
} from "@shared/types"

// Re-export shared types for consumers of the engine module
export type { PlatformOutput, UserSignalStrength, Prompt, User, ForumUser, Database }

// ==========================================================================
// AI & CONFIGURATION TYPES (Engine-Specific)
// ==========================================================================

/**
 * Represents the comprehensive AI configuration for a specific signal strength,
 * combining details from both the 'signal_strengths' and 'prompts' tables.
 */
export interface AiConfig {
    signalStrengthId: number
    model: string
    temperature: number
    maxChars: number
    prompts: Prompt[]
    maxValue: number
}

/**
 * Configuration for a generic AI model call.
 * This is distinct from AiConfig, which includes database-specific details and prompts.
 */
export interface ModelConfig {
    /** The identifier of the AI model to be used (e.g., "gpt-3.5-turbo"). */
    model: string
    /** The temperature setting for the AI model, controlling randomness. */
    temperature: number
    /** Optional: Maximum number of tokens to generate in the completion. */
    maxTokens?: number
}

/**
 * Represents the structured output from an AI service call.
 * This is a generic format before being mapped to specific database schemas like UserSignalStrength.
 */
export interface AIScoreOutput {
    /** The primary score value generated by the AI. */
    value?: number
    /** A one-sentence summary of the user's contribution. */
    summary: string
    /** A detailed paragraph describing the user's engagement, tone, and the substance of their posts. */
    description: string
    /** A paragraph with actionable suggestions for how the user could improve their contributions. */
    improvements: string
    /**
     * A paragraph explaining how the score was derived. For smart scores, this can be an object.
     */
    explained_reasoning: string | { value: number; reason: string }

    // --- Metadata related to the AI call execution ---
    /** The actual model identifier that was used for the call. */
    modelUsed: string
    /** Optional: The request ID from the AI provider, for tracing. */
    requestId?: string
    /** Optional: Number of tokens used in the prompt. */
    promptTokens?: number
    /** Optional: Number of tokens generated in the completion. */
    completionTokens?: number
}

// ==========================================================================
// SERVICE INTERFACES (Engine-Specific)
// ==========================================================================

/**
 * Interface for a generic AI service client.
 * Implementations of this interface will handle communication with specific AI providers.
 */
export interface AIServiceClient {
    /**
     * Sends a prompt to an AI model and expects a structured response.
     * @param prompt The fully constructed prompt string to send to the AI model.
     * @param modelConfig Configuration settings for the AI model.
     * @returns A Promise that resolves to an AIScoreOutput object.
     */
    getStructuredResponse(prompt: string, modelConfig: ModelConfig): Promise<AIScoreOutput>
}
