/**
 * @file Defines the core data structures and types for the Lambda Engine.
 * The most critical type is PlatformOutput, which is the standardized schema
 * that all platform adapters must return.
 */

import type { Database } from "@interfaces/supabase-types"

// ==========================================================================
// 1. CORE DATA STRUCTURES
// ==========================================================================

/**
 * The standardized data structure that all platform adapters must produce.
 * This schema is critical for ensuring zero disruption to downstream systems.
 * It is based on the original output of the legacy Discourse scripts.
 */
export interface PlatformOutput {
    /**
     * The unique identifier of the topic, post, or message from the source platform.
     * Can be a number (e.g., Discourse topic_id) or a string (e.g., Discord message ID).
     */
    topic_id: number | string

    /**
     * The username or identifier of the content author on the source platform.
     */
    author: string

    /**
     * The main text content of the post or message.
     */
    content: string

    /**
     * The creation timestamp of the content in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
     */
    timestamp: string

    /**
     * The number of replies to the content. Defaults to 0 if not applicable.
     */
    reply_count: number

    /**
     * The number of likes or reactions to the content. Defaults to 0 if not applicable.
     */
    like_count: number

    /**
     * An array of tags or keywords associated with the content.
     */
    tags: string[]

    /**
     * An optional field for any additional, platform-specific metadata that does not
     * fit into the core schema. This provides flexibility for future use cases.
     * Use with caution to avoid creating downstream dependencies on non-standard data.
     */
    metadata?: Record<string, any>
}

// ==========================================================================
// 2. SUPABASE-DERIVED TYPES
// These types are derived directly from the auto-generated Supabase schema
// to ensure perfect alignment with the database.
// ==========================================================================

/**
 * Represents the structure for inserting a new entry into the 'user_signal_strengths' table.
 * This is the primary data structure for storing AI-generated scores.
 */
export type UserSignalStrength = Database["public"]["Tables"]["user_signal_strengths"]["Insert"]

/**
 * Represents a row from the 'prompts' table.
 * Contains a specific prompt template and its metadata.
 */
export type Prompt = Database["public"]["Tables"]["prompts"]["Row"]

/**
 * Represents a row from the 'users' table.
 * Contains core information about a user across all platforms.
 */
export type User = Database["public"]["Tables"]["users"]["Row"]

/**
 * Represents a row from the 'forum_users' table.
 * This table links a user from the 'users' table to their platform-specific identity.
 */
export type ForumUser = Database["public"]["Tables"]["forum_users"]["Row"]

// ==========================================================================
// 3. AI & CONFIGURATION TYPES
// ==========================================================================

/**
 * Represents the comprehensive AI configuration for a specific signal strength,
 * combining details from both the 'signal_strengths' and 'prompts' tables.
 */
export interface AiConfig {
    signalStrengthId: number
    model: string
    temperature: number
    maxChars: number
    prompts: Prompt[]
    maxValue: number
}

/**
 * Configuration for a generic AI model call.
 * This is distinct from AiConfig, which includes database-specific details and prompts.
 */
export interface ModelConfig {
    /** The identifier of the AI model to be used (e.g., "gpt-3.5-turbo"). */
    model: string
    /** The temperature setting for the AI model, controlling randomness. */
    temperature: number
    /** Optional: Maximum number of tokens to generate in the completion. */
    maxTokens?: number
}

/**
 * Represents the structured output from an AI service call.
 * This is a generic format before being mapped to specific database schemas like UserSignalStrength.
 */
export interface AIScoreOutput {
    /** The primary score value generated by the AI. */
    value?: number
    /** A one-sentence summary of the user's contribution. */
    summary: string
    /** A detailed paragraph describing the user's engagement, tone, and the substance of their posts. */
    description: string
    /** A paragraph with actionable suggestions for how the user could improve their contributions. */
    improvements: string
    /** A paragraph explaining how the score was derived, referencing specific examples from the user's content. */
    explained_reasoning: string

    // --- Metadata related to the AI call execution ---
    /** The actual model identifier that was used for the call. */
    modelUsed: string
    /** Optional: The request ID from the AI provider, for tracing. */
    requestId?: string
    /** Optional: Number of tokens used in the prompt. */
    promptTokens?: number
    /** Optional: Number of tokens generated in the completion. */
    completionTokens?: number
}

// ==========================================================================
// 4. SERVICE INTERFACES
// ==========================================================================

/**
 * Interface for a generic AI service client.
 * Implementations of this interface will handle communication with specific AI providers.
 */
/**
 * Defines the standard interface for a platform-specific adapter.
 * The Engine Core interacts with this interface, allowing for loose coupling.
 */
export interface PlatformAdapter {
  /**
   * The main entry point for an adapter to process a single user.
   * @param userId The unique ID of the user to process.
   * @param projectId The ID of the project context to run against.
   * @param aiConfig The AI configuration for generating scores.
   */
  processUser(userId: string, projectId: number, aiConfig: AiConfig): Promise<void>;
}

export interface AIServiceClient {
    /**
     * Sends a prompt to an AI model and expects a structured response.
     * @param prompt The fully constructed prompt string to send to the AI model.
     * @param modelConfig Configuration settings for the AI model.
     * @returns A Promise that resolves to an AIScoreOutput object.
     */
    getStructuredResponse(prompt: string, modelConfig: ModelConfig): Promise<AIScoreOutput>
}
